[package]
name = "rs_zip"
version = "0.1.0"
authors = ["n-inokawa <48897392+n-inokawa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.16"

